### ISSUE TITLE
Pls update API 4.0.0 too

### ISSUE THREAD

**Issue by Gamerplau3975** [Muqsit/DimensionPortals#16]
Pls

**Comment by Muqsit** [comment]
For API 4, you may use Dev Build #50 which is the last build supporting PM 4: [NetherPortal_dev-50.phar](https://poggit.pmmp.io/r/185890/NetherPortal_dev-50.phar)

**Comment by Gamerplau3975** [comment]
It is crash server

пт, 2 июн. 2023 г., 06:42 Muqsit Rayyan ***@***.***>:

**Comment by Muqsit** [comment]
Can you paste the crashdump here
