### ISSUE TITLE
Does not work on pmmp 3.12.0

### ISSUE THREAD

**Issue by Mainek** [Muqsit/DimensionPortals#3]
[Server thread/ERROR]: Could not load plugin 'DimensionPortals': Incompatible API version (plugin requires one of: 4.0.0)
Плагин хороший но он не работает на pmmp .
Пожалуйста сделайте чтобы работало на pmmp 3.12.0 :)

**Comment by Muqsit** [comment]
The error is self explanatory.

**Comment by Mainek** [comment]
?

**Comment by Mainek** [comment]
Как мне получить pocketmine с api 4.0.0?

**Comment by Mainek** [comment]
Или сделайте поддержку для Api 3.12.0
