### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by xerenahmed** [Muqsit/DimensionPortals#8]
I think it originates from Minecraft, but I felt the need to open an issue. Broke down after 1.16.

Nether:
![nether](https://user-images.githubusercontent.com/35738714/90315858-5f12af00-df27-11ea-8b32-13169cffc950.png)

End:
![end](https://user-images.githubusercontent.com/35738714/90315859-5fab4580-df27-11ea-8aa1-475b5107c6de.png)

**Comment by Muqsit** [comment]
Yeah those are how the new nether and end dimensions look in 1.16 — vanilla behaviour
